import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Layout from '../components/layout/Layout'
import Hero from '../components/hero/Hero'
import { server } from '../db'
import Popular from '../components/popularMovie/Popular'
import UpComing from '../components/upcoming/UpComing'
import TopRated from '../components/toprated/TopRated'
import { ApiData } from '../utilss/ApiData'

const inter = Inter({ subsets: ['latin'] })

export default function Home( { topMoviesList, popularMoviesList, upcomingMoviesList}) {
  // console.log(popularMoviesList)
  return (
    <>
      <Head>
        <title>Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Layout>
          {/* <Hero /> */}
          <Popular popularMoviesList={popularMoviesList}   />
          <UpComing upcomingMoviesList={upcomingMoviesList} />
          <TopRated topMoviesList={topMoviesList} />
          
        </Layout>
      </>
    
       
    </>
  )
}

export const getStaticProps = async () => {
  const topMovies = await ApiData(`${server}/top_rated?api_key=${process.env.API_KEY}&language=en-US`)

  const popularMovies = await ApiData(`${server}/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`)

  const upComingMovies = await ApiData(`${server}/upcoming?api_key=${process.env.API_KEY}&language=en-US&page=1`)


  

  return{
    props: {
      topMoviesList: topMovies?.results,
      popularMoviesList: popularMovies?.results,
      upcomingMoviesList: upComingMovies?.results,
  
    }
  }
}
